---
# tasks file for ansible-role-nginx_reverse_proxy
- name: main | install nginx
  package:
    name: '{{ nginx_pkg_name }}'
    state: present
  tags:
    - package

- name: main | create nginx directories
  file:
    path: '{{ nginx_directory_created }}'
    state: directory
    owner: '{{ nginx_owner }}'
    group: '{{ nginx_group }}'
  loop_control:
    loop_var: nginx_directory_created
  with_items:
    - '{{ nginx_server_config_file | dirname }}'
    - '{{ nginx_proxy_config_file | dirname }}'
    - '{{ nginx_extra_config_dir }}'
    - '{{ nginx_locations_available_dir }}'
    - '{{ nginx_locations_enabled_dir }}'
    - '{{ nginx_sites_available_dir }}'
    - '{{ nginx_sites_enabled_dir }}'
    - '{{ nginx_ssl_dir }}'
    - '{{ nginx_systemd_custom_config | dirname }}'
  tags:
    - always

- name: main | template custom systemd service
  template:
    src: nginx.service.j2
    dest: '{{ nginx_systemd_custom_config }}'
    owner: '{{ nginx_owner }}'
    group: '{{ nginx_group }}'
  tags:
    - always

- name: main | template configuration file
  template:
    src: nginx.conf.j2
    dest: '{{ nginx_config_file }}'
    owner: '{{ nginx_owner }}'
    group: '{{ nginx_group }}'
  tags:
    - always

- name: main | copy extra configuration files
  copy:
    src: '{{ nginx_extra_config_file.src }}'
    dest: '{{ nginx_extra_config_file.dest }}'
    owner: '{{ nginx_owner }}'
    group: '{{ nginx_group }}'
  loop_control:
    loop_var: nginx_extra_config_file
  with_items:
    - src: server.conf
      dest: '{{ nginx_server_config_file }}'
    - src: proxy.conf
      dest: '{{ nginx_proxy_config_file }}'
  tags:
    - always

- name: main | include site configuration tasks
  include: site.yml
  loop_control:
    loop_var: nginx_site
  with_flattened:
    - server_name: '{{ nginx_server_name }}'
      use_ssl: '{{ nginx_use_ssl }}'
      ssl_key: '{{ nginx_ssl_key }}'
      ssl_cert: '{{ nginx_ssl_cert }}'
      enabled: yes
      includes: '{{ nginx_locations_enabled_dir }}/*.conf'
      include_default_locations: yes
    - '{{ nginx_sites }}'
  tags:
    - site
    - sites

- name: main | include location configuration tasks
  include: location.yml
  loop_control:
    loop_var: nginx_location
  with_items: '{{ nginx_locations }}'
  tags:
    - location
    - locations
